exports_files(glob(["*.bzl"]))

filegroup(
    name = "package-contents",
    srcs = glob(["*"]),
    visibility = ["//:__subpackages__"],
)
load("@bazel_skylib//rules:common_settings.bzl", "string_flag")

string_flag(
    name = "rpm_sign_key",
    build_setting_default = "",
    visibility = ["//visibility:public"],
)

string_flag(
    name = "rpm_sign_password",
    build_setting_default = "",
    visibility = ["//visibility:public"],
)
